In [3]:
import torch
# from namedtensor import ntorch

In [4]:
torch.ones(3,5).shape

torch.Size([3, 5])

In [6]:
q = torch.ones(3, 5, names=("batch", "vocab"))

..\c10/core/TensorImpl.h:806: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable.


In [7]:
q

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], names=('batch', 'vocab'))

In [13]:
VOCAB = 100
weight = torch.randn(VOCAB, requires_grad=True, names=("vocab", ))
weight.shape

torch.Size([100])

In [12]:
phi = torch.randn(VOCAB, names=("vocab",))
phi.shape

torch.Size([100])

In [15]:
weight.dot(phi)

tensor(12.6969, grad_fn=<DotBackward>)

In [16]:
from __future__ import print_function
import torch

# tensor

类似 numpy中的ndarray

In [18]:
x = torch.empty(5, 3)
print(x)

tensor([[4.2246e-39, 1.0286e-38, 1.0653e-38],
        [1.0194e-38, 8.4490e-39, 1.0469e-38],
        [9.3674e-39, 9.9184e-39, 8.7245e-39],
        [9.2755e-39, 8.9082e-39, 9.9184e-39],
        [8.4490e-39, 9.6429e-39, 1.0653e-38]])


In [21]:
y = torch.randn([4,3])
y

tensor([[ 0.1277,  1.8290, -1.1520],
        [ 0.1036,  1.8099,  0.4556],
        [-0.8566,  0.8811,  0.7955],
        [-0.2029, -0.0215,  0.6348]])

In [23]:
z = torch.rand(4,3)
z

tensor([[0.7217, 0.4340, 0.2868],
        [0.1320, 0.7800, 0.8856],
        [0.3371, 0.4346, 0.2634],
        [0.8302, 0.8960, 0.9470]])

In [27]:
x = torch.zeros(4,3, dtype=torch.int32)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [32]:
x = x.new_ones(4,3, dtype=torch.float32)
x.shape, x

(torch.Size([4, 3]),
 tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]))

In [33]:
y = torch.rand_like(x, dtype=torch.float32)
y

tensor([[0.0142, 0.6104, 0.0601],
        [0.7245, 0.7849, 0.6101],
        [0.8914, 0.1376, 0.9826],
        [0.5888, 0.8431, 0.1538]])

# operations

In [34]:
x+y

tensor([[1.0142, 1.6104, 1.0601],
        [1.7245, 1.7849, 1.6101],
        [1.8914, 1.1376, 1.9826],
        [1.5888, 1.8431, 1.1538]])

In [35]:
z = torch.add(x, y)
print(z)

tensor([[1.0142, 1.6104, 1.0601],
        [1.7245, 1.7849, 1.6101],
        [1.8914, 1.1376, 1.9826],
        [1.5888, 1.8431, 1.1538]])


In [36]:
result = torch.empty(4,3)
torch.add(x,y, out=result)

tensor([[1.0142, 1.6104, 1.0601],
        [1.7245, 1.7849, 1.6101],
        [1.8914, 1.1376, 1.9826],
        [1.5888, 1.8431, 1.1538]])

In [37]:
# inplace
y.add_(x)
y

tensor([[1.0142, 1.6104, 1.0601],
        [1.7245, 1.7849, 1.6101],
        [1.8914, 1.1376, 1.9826],
        [1.5888, 1.8431, 1.1538]])

In [39]:
y[:, 1]

tensor([1.6104, 1.7849, 1.1376, 1.8431])

**改变tensor形状，torch.view()**

In [46]:
x = torch.randn(24, dtype=torch.float32)
y = x.view(4, 6, 1)
z = y.view(-1, 3)
x.shape,y.shape, z.shape

(torch.Size([24]), torch.Size([4, 6, 1]), torch.Size([8, 3]))

In [48]:
one = torch.rand(1)
one.item(), one # Only one element tensor

(0.6236447095870972, tensor([0.6236]))

# Numpy Bridge

In [51]:
a = torch.ones(3, dtype=torch.int32)
b = a.numpy()
a, b

(tensor([1, 1, 1], dtype=torch.int32), array([1, 1, 1]))

In [52]:
import numpy as np

In [56]:
a = np.ones(4)
b = torch.from_numpy(a)
a, b, b+1, a+1

(array([1., 1., 1., 1.]),
 tensor([1., 1., 1., 1.], dtype=torch.float64),
 tensor([2., 2., 2., 2.], dtype=torch.float64),
 array([2., 2., 2., 2.]))

In [58]:
x.shape

torch.Size([24])

# CUDA tensor

In [59]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!    

tensor([ 0.3545,  0.7045,  1.0780,  2.0052,  0.4236, -0.0175,  1.4943, -0.3588,
        -0.5987,  1.4061,  0.5099,  0.6972,  1.7980,  1.5448,  0.5865,  0.9924,
         0.4448, -0.3915,  0.2202,  0.6943,  1.6363,  1.8067,  1.1608,  2.2460],
       device='cuda:0')
tensor([ 0.3545,  0.7045,  1.0780,  2.0052,  0.4236, -0.0175,  1.4943, -0.3588,
        -0.5987,  1.4061,  0.5099,  0.6972,  1.7980,  1.5448,  0.5865,  0.9924,
         0.4448, -0.3915,  0.2202,  0.6943,  1.6363,  1.8067,  1.1608,  2.2460],
       dtype=torch.float64)


# AUTOGRAD: AUTOMATIC DIFFERENTIATION

torch.Tensor, set its attribute .requires_grad as True

 finish your computation you can call .backward()
    
    accumulated into .grad attribute.

ensor and Function 

In [3]:
import torch

In [4]:
x = torch.ones(2,2, requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [5]:
y = x + 5
y

tensor([[6., 6.],
        [6., 6.]], grad_fn=<AddBackward0>)

In [6]:
# y was created as a result of an operation, so it has a grad_fn.
y.grad_fn

In [7]:
z = y*y*2
out = z.mean()
z,out

(tensor([[72., 72.],
         [72., 72.]], grad_fn=<MulBackward0>),
 tensor(72., grad_fn=<MeanBackward0>))

.requires_grad_( ... ) changes an existing Tensor’s requires_grad flag in-place. The input flag defaults to False if not given

In [8]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


**gradient**

out.backward() = out.backward(torch.tensor(1.)).

In [9]:
out.backward()

In [10]:
print(x.grad)

tensor([[6., 6.],
        [6., 6.]])


In [12]:
z.grad

In [13]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [21]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([-613.0301,  760.6616,  413.9593], grad_fn=<MulBackward0>)


In [22]:
y.backward

<bound method Tensor.backward of tensor([-613.0301,  760.6616,  413.9593], grad_fn=<MulBackward0>)>

In [23]:
print(x.grad)

None


# Define the network

In [24]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [33]:
class Net(nn.Module):
    
    def __init__(self):
        # 1 input image channel, 6 output channels, 3x3 square convolution
        # kernel
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1,6,3)
        self.conv2 = nn.Conv2d(6,16,3)
        
        # y = wx + b
        self.fc1 = nn.Linear(16*6*6, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)
        
    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x
    
    def num_flat_features(self, x):
        size = x.size()[1:]  # all dimensions except the batch dimension
        num_features = 1
        for s in size:
            num_features *= s
        return num_features
    

In [34]:
model = Net()
print(model)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=576, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [38]:
params = list(model.parameters())
print(len(params), params[0].shape)
params[1].shape

10 torch.Size([6, 1, 3, 3])


torch.Size([6])

In [39]:
x = torch.randn(1, 1, 32,32)
out = model(x)
print(out)

tensor([[ 0.0394,  0.0349,  0.0701, -0.1521, -0.0964, -0.1916,  0.1439, -0.0602,
         -0.0404,  0.0457]], grad_fn=<AddmmBackward>)


In [40]:
model.zero_grad()
out.backward(torch.randn(1, 10))

torch.nn only supports mini-batches. The entire torch.nn package only supports inputs that are a mini-batch of samples, and not a single sample.

For example, nn.Conv2d will take in a 4D Tensor of nSamples x nChannels x Height x Width.

If you have a single sample, just use input.unsqueeze(0) to add a fake batch dimension.

In [42]:
output = model(x)
target = torch.randn(10)  # a dummy target, for example
target = target.view(1, -1)  # make it the same shape as output
criterion = nn.MSELoss()

loss = criterion(output, target)
print(loss)

tensor(1.6615, grad_fn=<MseLossBackward>)


In [43]:
print(loss.grad_fn)  # MSELoss
print(loss.grad_fn.next_functions[0][0])  # Linear
print(loss.grad_fn.next_functions[0][0].next_functions[0][0])  # ReLU

In [46]:
model.zero_grad()     # zeroes the gradient buffers of all parameters

print('conv1.bias.grad before backward')
print(model.conv1.bias.grad)

loss.backward()

print('conv1.bias.grad after backward')
print(model.conv1.bias.grad)

conv1.bias.grad before backward
tensor([0., 0., 0., 0., 0., 0.])
conv1.bias.grad after backward
tensor([ 0.0253, -0.0051, -0.0080,  0.0213, -0.0082, -0.0254])


In [48]:
import torch.optim as optim

# create your optimizer
optimizer = optim.Adam(model.parameters(), lr=0.01)

# in your training loop:
optimizer.zero_grad()   # zero the gradient buffers
output = model(x)
loss = criterion(output, target)
loss.backward()
optimizer.step()    # Does the update